services:
  db:
    cpus: 1.0
    mem_limit: "1G"
    container_name: fractal-db
    image: postgres:15.4-alpine
    restart: always
    ports:
      - 5433:5433
    command: -p 5433
    environment:
      POSTGRES_USER: fractal
      POSTGRES_PASSWORD: fractal
      POSTGRES_DB: fractal
      # required for the check below - otherwise postgresql
      # will use undefined 'root' user and raise errors
      PGUSER: fractal
    healthcheck:
      # postgresql starts up, stops, and then restarts
      # => errors if the server connects before the stop
      # this checks if the system is ready
      test: pg_isready -p 5433
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - fractal

  slurm:
    hostname: slurm
    container_name: slurm
    cpus: 8.0
    mem_limit: 16g
    build:
      context: ../slurm-common
      dockerfile: Dockerfile
      args:
        - FRACTAL_SERVER_VERSION=2.15.1
        - SLURM_CPUS=8
        - SLURM_MEMORY=16000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /links/shared/scuanalysis/fractal/data/zarrs:/data/zarrs
      - /links/shared/scuanalysis/fractal/data/images:/data/images
      - /links/shared/scuanalysis:/scuanalysis:ro
    environment:
      - SLURM_CPUS_ON_NODE=1
    ports:
      - 8000:8000
      - 6817:6817
      - 6818:6818
    healthcheck:
      test: wget http://slurm:8000/api/alive/ > /dev/null 2>&1
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - fractal

  web:
    container_name: fractal-web
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - FRACTAL_WEB_VERSION=1.19.1
    depends_on:
      slurm:
        condition: service_healthy
    ports:
      - 5173:5173
    networks:
      - fractal

  server-config:
    container_name: server-config
    user: "650186:456709"
    build:
      context: ./server-config
      args:
        - FRACTAL_CLIENT_VERSION=2.9.1
    depends_on:
      slurm:
        condition: service_healthy
    volumes:
      - /links/shared/scuanalysis/fractal/data:/data
      # data:/data
    networks:
      - fractal

  fractal-filebrowser:
    container_name: fractal-filebrowser
    user: "650186:456709"
    build:
      context: ./filebrowser
    ports:
      - 8080:80
    networks:
      - fractal
    volumes:
      - /links/shared/scuanalysis/fractal/data:/data

  fractal-data:
    container_name: fractal-data
    user: "650186:456709"
    image: ghcr.io/fractal-analytics-platform/fractal-data:dev
    environment:
      - FRACTAL_SERVER_URL=http://slurm:8000
      - AUTHORIZATION_SCHEME=fractal-server
    ports:
      - 3000:3000
    networks:
      - fractal
    volumes:
      - /links/shared/scuanalysis/fractal/data:/data:ro

  fractal-feature-explorer:
    container_name: fractal-feature-explorer
    build:
      context: ./dashboard
      args:
        - FRACTAL_FEATURE_EXPLORER_VERSION=0.1.9
    depends_on:
      slurm:
        condition: service_healthy
    ports:
      - 8501:8501
    networks:
      - fractal

volumes:
  data:
  postgres_db:

networks:
  fractal:
    driver: bridge
